### ISSUE TITLE
It needs to apply responsive system like Bootstrap 4.

### ISSUE THREAD

**Issue by rdxxer** [namumag/namumag.github.io#4]
I got an issue.

Sans wrote, 
"The space between the rows seems narrow."

And I found out that Sans uses a tablet.
It seems to non-reponsible system causes some problems.

I'd appreciate it if you could handle it.

**Comment by namumag** [comment]
THX. I'm going to try that.

**Comment by namumag** [comment]
I'm going to close this. I'll mention you in [https://github.com/namumag/namumag.github.io/projects/1](project page).
